# This is a basic workflow to help you get started with Actions

name: Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    container: 'pandoc/core:2.9.2.1'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: install dependencies
      run: apk --no-cache add make
  
    - name: generate by pandoc
      run: for x in `find . -type d -maxdepth 1 |egrep -v 'docs|.git|^\.$'`; do cd $x; make; cd ..; mkdir -p docs/$x; cp $x/index.html docs/$x/; done

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: master  # deploying branch
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
